### PR TITLE
Remove smooth scroll and use hash history

### PR DESCRIPTION
**Pull request by uttrasey**
- Gets deep linking working by switching history implementation
- Removes subsection links (which were inadvertently broken by switching to hash)

### CODE REVIEW

**Comment by kaw2k** [comment]
Two things:

1) We need to keep the concept of the basePath. Before it was handled by our history, we need to move that logic to our routes file now. This needs to happen as our base path changes when we run locally vas when we run via gh-pages. Conditionally setting the path of the root route should solve this.

2) As I think about this, we may want to keep the subsections on the sidebar and just make them not links. Thy can directly scroll to the target element without setting the hash.

**Comment by uttrasey** [comment]
> 1) We need to keep the concept of the basePath. Before it was handled by our history, we need to move that logic to our routes file now. This needs to happen as our base path changes when we run locally vas when we run via gh-pages. Conditionally setting the path of the root route should solve this.

I was trying to figure out what `useBasename` was doing. I deployed this code (without baseName) and everything was working both locally and remotely so decided maybe it was surplus. 

> 2) As I think about this, we may want to keep the subsections on the sidebar and just make them not links. Thy can directly scroll to the target element without setting the hash.

Sounds like a plan. I'll add them back without link behaviour for now.

**Comment by kaw2k** [comment]
It only becomes a problem when you refresh (I think, lololol). Perhaps I am crazy. No worries, sorry for sending you down holes if it isn't indeed a problem.

**Comment by uttrasey** [comment]
@kaw2k lol no problem, I've added subsections back (just text not links) for now. Sounds like there is a possibility I'll break the deep linking / refresh but if I do... I'll try and fix it :smiley:

**Comment by kaw2k** [comment]
Sounds good to me :smile:

**Pull request merged**
