### PR TITLE
Not submitting the form if enter key is pressed with-in textarea

### PR DESCRIPTION
**Pull request by ashokkumar**

### CODE REVIEW

**Comment by kaw2k** [comment]
Thank you for your PR @ashokkumar! :smile: 

This is actually desired functionality. The `textarea` component should allow the user to enter freeform text (including line breaks) without submitting the form. I am not sure about your use case, would a regular `input` work for you? 

If you _really_ needed a `textarea` to behave in this fashion, you could easily write a custom `Textarea` component to submit itself when it detects the user pressing enter.

**Comment by kaw2k** [comment]
I totally misread the intent of the PR! I thought it was reversed. Sorry for the confusion. 

@ashokkumar, I have never come across this issue with `textarea`s submitting on enter. Mind writing up a test to document this issue as well?

**Comment by ashokkumar** [comment]
Hi Kevin, thanks for your response.
I added a TextArea component and when I hit enter from inside it, the onKeyDown event in form.js is called and the form is getting submitted. So I added the extra condition to onKeyDown to check the event target type, which fixed the issue for me.

I will write a test for it and update you.

**Comment by killerswan** [comment]
Hmm, yeah, just hit this.

**Comment by kaw2k** [comment]
Should be fixed in v2

**Pull request closed without merging**
